### PR TITLE
 Linux (proton) support + Adapt README.md

### PR DESCRIPTION
**Pull request by SpeedeKowskyy**
- Added Linux proton support.
- Changed README.md

### CODE REVIEW

**Review by heyngra — COMMENTED** [review]
Please test it, with the commits that I made:
04f168df17d72c8367aa0ef02387752482b1872f
2b285ef2a8d27141b7a0376da354c87caa7c1b59
ed2abc75a071a0ecf5b3c3c9ab89047a7b6ece5a

**Review by heyngra — COMMENTED** [review]
Check on Linux, if it works correctly, if so it's ready to merge.

**Comment by SpeedeKowskyy** [comment]
Works.

**Comment by heyngra** [comment]
Great! :D

**Pull request merged**
